### ISSUE TITLE
File "yolo_opencv.py", line 39, in draw_prediction

### ISSUE THREAD

**Issue by vascobarbosa** [arunponnusamy/object-detection-opencv#14]
Mac OSX 10.14.1 (18B75)

Traceback (most recent call last):
  File "yolo_opencv.py", line 98, in <module>
    draw_prediction(image, class_ids[i], confidences[i], round(x), round(y), round(x+w), round(y+h))
  File "yolo_opencv.py", line 39, in draw_prediction
    cv2.rectangle(img, (x,y), (x_plus_w,y_plus_h), color, 2)
TypeError: only length-1 arrays can be converted to Python scalars

**Comment by arunponnusamy** [comment]
May I know the OpenCV and Python version you are working with ?

**Comment by ziane-fawzi** [comment]
Hi i have the same problem
I use OpenCV 4.5.1 python3

can you help me please ?
