### ISSUE TITLE
'module' has no 'readNet'

### ISSUE THREAD

**Issue by bebe04** [arunponnusamy/object-detection-opencv#8]
hi,

i'm trying to use yolo but when i use the command 
`$ python yolo_opencv.py --image dog.jpg --config yolov3.cfg --weights yolov3.weights --classes yolov3.txt`

i get the following error
```
Traceback (most recent call last):
  File "yolo_opencv.py", line 57, in <module>
    net = cv2.dnn.readNet(args.weights, args.config)
AttributeError: 'module' object has no attribute 'readNet'
```

i'm using python 2.7.12

if I use python 3
 `$ python3 yolo_opencv.py --image dog.jpg --config yolov3.cfg --weights yolov3.weights --classes yolov3.txt` i get this error

```
Traceback (most recent call last):
  File "yolo_opencv.py", line 8, in <module>
    import cv2
ImportError: /opt/ros/kinetic/lib/python2.7/dist-packages/cv2.so: undefined symbol: PyCObject_Type
```

how can i solve this error? (both would be nice, i would like to use python3 if it's possible)

**Comment by shaarkrat2** [comment]
you probably have a problem with python3. Try to uninstall it

**Comment by arunponnusamy** [comment]
Hello @bebe04 , install the dependencies using `pip3` and run the script using `python3`.
`pip install numpy opencv-python`
 `python3 yolo_opencv.py --image dog.jpg --config yolov3.cfg --weights yolov3.weights --classes yolov3.txt`

**Comment by peuris** [comment]
@bebe04 I had the same problem with python 2.7 and opencv 3.3.0. 

>  net = cv2.dnn.readNet(args.weights, args.config)
AttributeError: 'module' object has no attribute 'readNet'

 I installed OpenCV 4.0.0 and this fixed the problem with readNet. According to OpenCV -> readNet compatibility > OpenCV3.3: https://docs.opencv.org/4.0.0/d6/d0f/group__dnn.html#ga3b34fe7a29494a6a4295c169a7d32422

**Comment by nand22** [comment]
@arunponnusamy exactly the same problem here as @bebe04. I tried all the suggestions, nothing seems to work so far.

**Comment by arunponnusamy** [comment]
@nand22  May I know the Python and OpenCV version you are working with and the command you are trying to execute ?

**Comment by sundharsk** [comment]
error:
  
![err](https://user-images.githubusercontent.com/46772827/55617470-cb1cc900-57b1-11e9-9bc8-873ecb49323c.jpg)

**Comment by trantuanvu1602** [comment]
modify **cv2.dnn.readNet** to **cv2.dnn.readNetFromDarknet**

**Comment by arunponnusamy** [comment]
@sundharsk May I know the Python and OpenCV version you are working with ?

**Comment by anamika06jain** [comment]
@arunponnusamy  i am having python version 3.5.5 and openCV version 3.4.1. I am also having the same problem. please suggest the way to solve this.

**Comment by arunponnusamy** [comment]
Try with the latest version of OpenCV. That should solve the issue I hope.

**Comment by anamika06jain** [comment]
@arunponnusamy  Now New error is coming " error: (-2:Unspecified error) Cannot determine an origin framework of files:  in function 'cv::dnn::dnn4_v20190122::readNet'"

**Comment by Rishan123** [comment]
how do I update OpenCV?

**Comment by Rishan123** [comment]
Using Raspberry Pi 3 and Python3

**Comment by Rishan123** [comment]
> modify **cv2.dnn.readNet** to **cv2.dnn.readNetFromDarknet**

I tried that and it still got an error, this time:

`Traceback (most recent call last):
  File "yolo.py", line 34, in <module>
    net = cv2.dnn.readNetFromDarknet(args.weights, args.config)
AttributeError: module 'cv2.dnn' has no attribute 'readNetFromDarknet'
`

**Comment by anamika06jain** [comment]
I also has the problem. Updation of opencev version helps me.

**Comment by Rishan123** [comment]
Can you please tell me how to update opencv?

**Comment by anamika06jain** [comment]
What version of opencev u r using?

**Comment by Rishan123** [comment]
3

**Comment by anamika06jain** [comment]
Update that with opencv 4. U can use uodate command or just write pip
install opencv4.0

**Comment by Rishan123** [comment]
I tried that, but I got:

`ERROR: Could not find a version that satisfies the requirement opencv4.0 (from versions: none)
ERROR: No matching distribution found for opencv4.0
`

**Comment by Rishan123** [comment]
Using Raspberry Pi

**Comment by anamika06jain** [comment]
I have not tried that on raspbery pi.. i was doing that on windows system.

**Comment by Rishan123** [comment]
It should probably be the same.

**Comment by Rishan123** [comment]
I found another website, that usses pi 3b:

[http://funofdiy.blogspot.com/2018/08/deep-learning-with-raspberry-pi-real.html](http://funofdiy.blogspot.com/2018/08/deep-learning-with-raspberry-pi-real.html)

**Comment by Murilo-ZC** [comment]
> Can you please tell me how to update opencv?

For me I have to uninstall my older version of OpenCv and them reinstall version 4. Solved my problem with dnn.readNet() not found (Windows).

**Comment by hunaidkhan2000** [comment]
Use pip install opencv-python==4.0.0.21  should resolve your issue

**Comment by sarath0993** [comment]
Upgrading opencv from 3.4.1 to 4.1.1 resolved this issue. 

_Download and install latest opencv WHL file from here >>_ [Latest OpenCV](https://pypi.org/project/opencv-python/#files)

**Comment by Marshajennifer** [comment]
C:\Users\User\anomaly>python yolo_opencv.py --image dog.jpg --config yolov3.cfg --weights yolov3.weights --classes yolov3.txt

i get the following error:

Traceback (most recent call last):
  File "yolo_opencv.py", line 57, in <module>
    net = cv2.dnn.readNet(args.weights, args.config)
cv2.error: OpenCV(4.1.2) C:\projects\opencv-python\opencv\modules\dnn\src\darknet\darknet_importer.cpp:214: error: (-212:Parsing error) Failed to parse NetParameter file: yolov3.weights in function 'cv::dnn::dnn4_v20190902::readNetFromDarknet'

**Comment by gfesquivelt** [comment]
Since I couldn't update opencv using Python 3.6, my solution was to create a new environment with Python 3.7 and it allowed me to install a recent opencv version.

**Comment by HebaGamalElDin** [comment]
Hi, 
I'm using YOLO Pre-trained model for live video streams, i got this error::
`error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\dnn\src\darknet\darknet_io.cpp:677: error: (-212:Parsing error) Unknown layer type:  in function 'cv::dnn::darknet::ReadDarknetFromCfgStream'`

**Comment by Mimun** [comment]
> readNetFromDarknet

error: OpenCV(4.2.0) /io/opencv/modules/dnn/src/darknet/darknet_importer.cpp:207: error: (-212:Parsing error) Failed to parse NetParameter file: yolov3.weights in function 'readNe

**Comment by fatima598** [comment]
> > readNetFromDarknet
> 
> error: OpenCV(4.2.0) /io/opencv/modules/dnn/src/darknet/darknet_importer.cpp:207: error: (-212:Parsing error) Failed to parse NetParameter file: yolov3.weights in function 'readNe

dawnload another file of yolov3.weights

**Comment by psk1998** [comment]
> Hi,
> I'm using YOLO Pre-trained model for live video streams, i got this error::
> `error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\dnn\src\darknet\darknet_io.cpp:677: error: (-212:Parsing error) Unknown layer type: in function 'cv::dnn::darknet::ReadDarknetFromCfgStream'`

I got the same error, how did you fix it?
